import NavBar from '@/components/navbar/NavBar';
import { ChildrenProps } from '@/interfaces/interface';
import '@/styles/globals.css';
import { Montserrat } from 'next/font/google';
import Footer from './footer';
import { useLocale } from 'next-intl';
import { notFound } from 'next/navigation';
import { I18nProvider } from '@/context/i18nContext';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children, params }: ChildrenProps) {
  const locale = useLocale();
  // console.log(locale);
  // console.log(params?.locale);

  if (params?.locale !== locale) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body
        className={`${montserrat.className} dark:bg-[#1A202C]`}
        suppressHydrationWarning={true}>
        <I18nProvider locale={locale}>
          <header>
            <NavBar />
          </header>
          <main>{children}</main>
          <Footer />
        </I18nProvider>
      </body>
    </html>
  );
}
